window.SkillNestData = {
  taskChips: [
    "Build a simple AI website",
    "Create Instagram posts from a menu",
    "Organize customer data",
    "Write product descriptions",
    "Design a menu",
    "Automate repetitive admin work",
  ],

  tasks: [
    {
      id: "restaurant-content-hatch",
      title: "Create 30 Instagram posts from a menu",
      business: "Cafe",
      objective: "Turn one menu into 30 Instagram posts.",
      budget: "$60 - $120",
      timeline: "2 days",
      estimatedCompletion: "2 days",
      level: "L1",
      industry: "Restaurant",
      category: "Restaurant",
      status: "New Hatch",
      description: "Turn a cafe menu into a month of simple Instagram captions, including daily specials and light promo posts.",
      deliverables: ["30 captions", "Hashtag suggestions", "Posting notes"],
    },
    {
      id: "salon-website-hatch",
      title: "Build a one-page website for a nail salon",
      business: "Nail salon",
      objective: "Create a clean one-page website with services, pricing, and booking.",
      budget: "$250 - $500",
      timeline: "1 week",
      estimatedCompletion: "1 week",
      level: "L2",
      industry: "Local Services",
      category: "Local Services",
      status: "Incubating",
      description: "Create a clean one-page website with services, pricing, booking link, and contact details.",
      deliverables: ["Page copy", "Layout draft", "Mobile-friendly structure"],
    },
    {
      id: "product-description-hatch",
      title: "Rewrite product descriptions",
      business: "Online store",
      objective: "Rewrite product descriptions so customers can compare items faster.",
      budget: "$150 - $350",
      timeline: "4 days",
      estimatedCompletion: "4 days",
      level: "L2",
      industry: "E-commerce",
      category: "E-commerce",
      status: "New Hatch",
      description: "Rewrite product descriptions so they are clearer, more searchable, and easier for customers to compare.",
      deliverables: ["Updated descriptions", "SEO title suggestions", "Tone cleanup"],
    },
    {
      id: "customer-data-hatch",
      title: "Organize customer contacts in Google Sheets",
      business: "Service business",
      objective: "Clean customer contacts into a usable Google Sheets system.",
      budget: "$80 - $180",
      timeline: "3 days",
      estimatedCompletion: "3 days",
      level: "L1",
      industry: "Local Services",
      category: "Local Services",
      status: "Hatched",
      description: "Clean and organize customer contact data into usable columns with duplicate checks.",
      deliverables: ["Clean spreadsheet", "Column structure", "Duplicate notes"],
    },
    {
      id: "restaurant-menu-hatch",
      title: "Design a restaurant menu",
      business: "Restaurant",
      objective: "Design a readable menu with polished item descriptions.",
      budget: "$150 - $300",
      timeline: "3 days",
      estimatedCompletion: "3 days",
      level: "L2",
      industry: "Restaurant",
      category: "Restaurant",
      status: "New Hatch",
      description: "Create a readable menu layout with polished item descriptions and clear categories.",
      deliverables: ["Menu copy", "Canva layout", "Editable file"],
    },
    {
      id: "customer-support-hatch",
      title: "Set up customer support replies",
      business: "Online store",
      objective: "Build an AI chatbot using the store FAQ.",
      budget: "$90 - $180",
      timeline: "2 days",
      estimatedCompletion: "2 days",
      level: "L2",
      industry: "E-commerce",
      category: "Customer Support",
      status: "Incubating",
      description: "Turn existing FAQ content into a lightweight chatbot outline and reusable customer reply templates.",
      deliverables: ["Reply library", "Chatbot flow", "FAQ grouping"],
    },
    {
      id: "booking-workflow-hatch",
      title: "Set up a simple booking workflow",
      business: "Barber shop",
      objective: "Set up a simple request workflow using Google Forms and Sheets.",
      budget: "$180 - $380",
      timeline: "5 days",
      estimatedCompletion: "5 days",
      level: "L3",
      industry: "Local Services",
      category: "Operations",
      status: "Incubating",
      description: "Set up a booking request workflow using Google Forms, Sheets, and basic notification steps.",
      deliverables: ["Form", "Tracking sheet", "Workflow notes"],
    },
    {
      id: "tutoring-faq-hatch",
      title: "Create FAQ replies for a tutoring business",
      business: "Tutoring studio",
      objective: "Create polished replies for parent questions about sessions and pricing.",
      budget: "$70 - $150",
      timeline: "2 days",
      estimatedCompletion: "2 days",
      level: "L1",
      industry: "Education",
      category: "Education",
      status: "New Hatch",
      description: "Create short replies for parents asking about pricing, scheduling, subjects, and trial sessions.",
      deliverables: ["FAQ replies", "Inquiry templates", "Follow-up copy"],
    },
    {
      id: "real-estate-lead-hatch",
      title: "Create a real estate lead workflow",
      business: "Real estate agency",
      objective: "Create an automated lead qualification workflow.",
      budget: "$300 - $700",
      timeline: "1 week",
      estimatedCompletion: "1 week",
      level: "L3",
      industry: "Real Estate",
      category: "Real Estate",
      status: "Hatched",
      description: "Create a simple lead qualification workflow that sorts buyer and seller inquiries into clear next steps.",
      deliverables: ["Lead form", "Qualification logic", "Follow-up templates"],
    },
    {
      id: "shopify-titles-hatch",
      title: "Improve Shopify product titles",
      business: "Shopify store",
      objective: "Improve product titles and short descriptions for search and scanning.",
      budget: "$120 - $260",
      timeline: "3 days",
      estimatedCompletion: "3 days",
      level: "L2",
      industry: "E-commerce",
      category: "E-commerce",
      status: "Hatched",
      description: "Improve product titles and short descriptions for clarity, search, and customer scanning.",
      deliverables: ["Updated titles", "Short descriptions", "Keyword notes"],
    },
  ],

  hatchedWork: [
    {
      title: "Restaurant marketing package",
      category: "Restaurant",
      outputs: ["30 Instagram posts", "12 Reels", "Canva templates", "Prompt library"],
      timeSaved: "18 hours",
      status: "Hatched",
    },
    {
      title: "Shopify product cleanup",
      category: "E-commerce",
      outputs: ["Updated product titles", "Short descriptions", "SEO notes", "Tone guide"],
      timeSaved: "9 hours",
      status: "Hatched",
    },
    {
      title: "Real estate lead workflow",
      category: "Real Estate",
      outputs: ["Lead form", "Qualification workflow", "Reply templates", "Tracking sheet"],
      timeSaved: "14 hours",
      status: "Hatched",
    },
  ],

  operators: [
    {
      id: "maya-chen",
      name: "Maya Chen",
      initials: "MC",
      level: "L2 Hatcher",
      completed: 18,
      rating: "4.9",
      onTime: "94%",
      industries: ["Restaurant", "Local Services"],
      tools: ["ChatGPT", "Canva", "Notion"],
      bio: "Creates clear content, menus, and admin systems for small local businesses.",
      offers: [
        { title: "Restaurant menu rewrite", industry: "Restaurant", level: "L2", status: "Hatched" },
        { title: "Cafe caption pack", industry: "Restaurant", level: "L1", status: "Hatched" },
        { title: "Salon service page", industry: "Local Services", level: "L2", status: "Hatched" },
      ],
    },
    {
      id: "eli-morgan",
      name: "Eli Morgan",
      initials: "EM",
      level: "L3 Specialist",
      completed: 31,
      rating: "4.8",
      onTime: "91%",
      industries: ["E-commerce", "Education"],
      tools: ["Claude", "Zapier", "Sheets"],
      bio: "Helps online stores and education teams organize content, workflows, and data.",
      offers: [
        { title: "Shopify product cleanup", industry: "E-commerce", level: "L2", status: "Hatched" },
        { title: "Tutor FAQ system", industry: "Education", level: "L1", status: "Hatched" },
        { title: "Order status workflow", industry: "E-commerce", level: "L3", status: "Hatched" },
      ],
    },
    {
      id: "samira-patel",
      name: "Samira Patel",
      initials: "SP",
      level: "L2 Hatcher",
      completed: 22,
      rating: "4.9",
      onTime: "96%",
      industries: ["Real Estate", "Local Services"],
      tools: ["ChatGPT", "Canva", "Notion"],
      bio: "Turns messy service-business requests into polished copy, templates, and client-facing assets.",
      offers: [
        { title: "Property listing rewrite", industry: "Real Estate", level: "L2", status: "Hatched" },
        { title: "Cleaning service replies", industry: "Local Services", level: "L1", status: "Hatched" },
        { title: "Local flyer copy", industry: "Local Services", level: "L2", status: "Hatched" },
      ],
    },
  ],

  levels: [
    ["L1", "Simple support Hatches", "Clear, low-risk work like captions, formatting, summaries, and data cleanup."],
    ["L2", "Practical business Hatches", "Useful deliverables like simple websites, menus, product copy, and reply templates."],
    ["L3", "Specialized Hatches", "More complex setup work like automations, content systems, and workflow improvements."],
    ["L4", "Advanced strategy", "Higher-trust strategic work. Coming later."],
  ],
};
