window.SkillNestData = {
  taskChips: [
    "Build a simple AI website",
    "Create Instagram posts from a menu",
    "Organize customer data",
    "Write product descriptions",
    "Design a menu",
    "Automate repetitive admin work",
  ],

  tasks: [
    {
      id: "restaurant-content-hatch",
      title: "Create 30 Instagram posts from a menu",
      business: "Cafe",
      objective: "Turn one menu into 30 Instagram posts.",
      budget: "$60 - $120",
      timeline: "2 days",
      estimatedCompletion: "2 days",
      level: "L1",
      industry: "Restaurant",
      category: "Restaurant",
      status: "New Hatch",
      description: "Turn a cafe menu into a month of simple Instagram captions, including daily specials and light promo posts.",
      deliverables: ["30 captions", "Hashtag suggestions", "Posting notes"],
    },
    {
      id: "salon-website-hatch",
      title: "Build a one-page website for a nail salon",
      business: "Nail salon",
      objective: "Create a clean one-page website with services, pricing, and booking.",
      budget: "$250 - $500",
      timeline: "1 week",
      estimatedCompletion: "1 week",
      level: "L2",
      industry: "Local Services",
      category: "Local Services",
      status: "Incubating",
      description: "Create a clean one-page website with services, pricing, booking link, and contact details.",
      deliverables: ["Page copy", "Layout draft", "Mobile-friendly structure"],
    },
    {
      id: "product-description-hatch",
      title: "Rewrite product descriptions",
      business: "Online store",
      objective: "Rewrite product descriptions so customers can compare items faster.",
      budget: "$150 - $350",
      timeline: "4 days",
      estimatedCompletion: "4 days",
      level: "L2",
      industry: "E-commerce",
      category: "E-commerce",
      status: "New Hatch",
      description: "Rewrite product descriptions so they are clearer, more searchable, and easier for customers to compare.",
      deliverables: ["Updated descriptions", "SEO title suggestions", "Tone cleanup"],
    },
    {
      id: "customer-data-hatch",
      title: "Organize customer contacts in Google Sheets",
      business: "Service business",
      objective: "Clean customer contacts into a usable Google Sheets system.",
      budget: "$80 - $180",
      timeline: "3 days",
      estimatedCompletion: "3 days",
      level: "L1",
      industry: "Local Services",
      category: "Local Services",
      status: "Hatched",
      description: "Clean and organize customer contact data into usable columns with duplicate checks.",
      deliverables: ["Clean spreadsheet", "Column structure", "Duplicate notes"],
    },
    {
      id: "restaurant-menu-hatch",
      title: "Design a restaurant menu",
      business: "Restaurant",
      objective: "Design a readable menu with polished item descriptions.",
      budget: "$150 - $300",
      timeline: "3 days",
      estimatedCompletion: "3 days",
      level: "L2",
      industry: "Restaurant",
      category: "Restaurant",
      status: "New Hatch",
      description: "Create a readable menu layout with polished item descriptions and clear categories.",
      deliverables: ["Menu copy", "Canva layout", "Editable file"],
    },
    {
      id: "customer-support-hatch",
      title: "Set up customer support replies",
      business: "Online store",
      objective: "Build an AI chatbot using the store FAQ.",
      budget: "$90 - $180",
      timeline: "2 days",
      estimatedCompletion: "2 days",
      level: "L2",
      industry: "E-commerce",
      category: "Customer Support",
      status: "Incubating",
      description: "Turn existing FAQ content into a lightweight chatbot outline and reusable customer reply templates.",
      deliverables: ["Reply library", "Chatbot flow", "FAQ grouping"],
    },
    {
      id: "booking-workflow-hatch",
      title: "Set up a simple booking workflow",
      business: "Barber shop",
      objective: "Set up a simple request workflow using Google Forms and Sheets.",
      budget: "$180 - $380",
      timeline: "5 days",
      estimatedCompletion: "5 days",
      level: "L3",
      industry: "Local Services",
      category: "Operations",
      status: "Incubating",
      description: "Set up a booking request workflow using Google Forms, Sheets, and basic notification steps.",
      deliverables: ["Form", "Tracking sheet", "Workflow notes"],
    },
    {
      id: "tutoring-faq-hatch",
      title: "Create FAQ replies for a tutoring business",
      business: "Tutoring studio",
      objective: "Create polished replies for parent questions about sessions and pricing.",
      budget: "$70 - $150",
      timeline: "2 days",
      estimatedCompletion: "2 days",
      level: "L1",
      industry: "Education",
      category: "Education",
      status: "New Hatch",
      description: "Create short replies for parents asking about pricing, scheduling, subjects, and trial sessions.",
      deliverables: ["FAQ replies", "Enquiry templates", "Follow-up copy"],
    },
    {
      id: "real-estate-lead-hatch",
      title: "Create a real estate lead workflow",
      business: "Real estate agency",
      objective: "Create an automated lead qualification workflow.",
      budget: "$300 - $700",
      timeline: "1 week",
      estimatedCompletion: "1 week",
      level: "L3",
      industry: "Real Estate",
      category: "Real Estate",
      status: "Hatched",
      description: "Create a simple lead qualification workflow that sorts buyer and seller enquiries into clear next steps.",
      deliverables: ["Lead form", "Qualification logic", "Follow-up templates"],
    },
    {
      id: "shopify-titles-hatch",
      title: "Improve Shopify product titles",
      business: "Shopify store",
      objective: "Improve product titles and short descriptions for search and scanning.",
      budget: "$120 - $260",
      timeline: "3 days",
      estimatedCompletion: "3 days",
      level: "L2",
      industry: "E-commerce",
      category: "E-commerce",
      status: "Hatched",
      description: "Improve product titles and short descriptions for clarity, search, and customer scanning.",
      deliverables: ["Updated titles", "Short descriptions", "Keyword notes"],
    },
  ],

  hatchedWork: [
    {
      title: "Restaurant marketing package",
      category: "Restaurant",
      outputs: ["30 Instagram posts", "12 Reels", "Canva templates", "Prompt library"],
      timeSaved: "18 hours",
      status: "Hatched",
    },
    {
      title: "Shopify product cleanup",
      category: "E-commerce",
      outputs: ["Updated product titles", "Short descriptions", "SEO notes", "Tone guide"],
      timeSaved: "9 hours",
      status: "Hatched",
    },
    {
      title: "Real estate lead workflow",
      category: "Real Estate",
      outputs: ["Lead form", "Qualification workflow", "Reply templates", "Tracking sheet"],
      timeSaved: "14 hours",
      status: "Hatched",
    },
  ],

  operators: [
    {
      id: "maya-chen",
      name: "Maya Chen",
      initials: "MC",
      level: "L2 Hatcher",
      completed: 18,
      rating: "4.9",
      onTime: "94%",
      industries: ["Restaurant", "Local Services"],
      tools: ["ChatGPT", "Canva", "Notion"],
      bio: "Creates clear content, menus, and admin systems for small local businesses.",
      offers: [
        { title: "Restaurant menu rewrite", industry: "Restaurant", level: "L2", status: "Hatched" },
        { title: "Cafe caption pack", industry: "Restaurant", level: "L1", status: "Hatched" },
        { title: "Salon service page", industry: "Local Services", level: "L2", status: "Hatched" },
      ],
    },
    {
      id: "eli-morgan",
      name: "Eli Morgan",
      initials: "EM",
      level: "L3 Specialist",
      completed: 31,
      rating: "4.8",
      onTime: "91%",
      industries: ["E-commerce", "Education"],
      tools: ["Claude", "Zapier", "Sheets"],
      bio: "Helps online stores and education teams organize content, workflows, and data.",
      offers: [
        { title: "Shopify product cleanup", industry: "E-commerce", level: "L2", status: "Hatched" },
        { title: "Tutor FAQ system", industry: "Education", level: "L1", status: "Hatched" },
        { title: "Order status workflow", industry: "E-commerce", level: "L3", status: "Hatched" },
      ],
    },
    {
      id: "samira-patel",
      name: "Samira Patel",
      initials: "SP",
      level: "L2 Hatcher",
      completed: 22,
      rating: "4.9",
      onTime: "96%",
      industries: ["Real Estate", "Local Services"],
      tools: ["ChatGPT", "Canva", "Notion"],
      bio: "Turns messy service-business requests into polished copy, templates, and client-facing assets.",
      offers: [
        { title: "Property listing rewrite", industry: "Real Estate", level: "L2", status: "Hatched" },
        { title: "Cleaning service replies", industry: "Local Services", level: "L1", status: "Hatched" },
        { title: "Local flyer copy", industry: "Local Services", level: "L2", status: "Hatched" },
      ],
    },
  ],

  hatcherProfiles: [
    {
      id: "toby-cheng",
      name: "Toby Cheng",
      initials: "TC",
      level: "L2 Hatcher",
      rating: "4.9",
      completedCount: 32,
      joinedAt: "Mar 2026",
      specialization: "Restaurant Specialist",
      skills: ["ChatGPT", "Canva", "Notion", "Website copy", "Social content"],
      industries: ["Restaurant", "Local Services"],
      averageCompletion: "2.3 days",
      totalEarned: "$3,840",
      recentWorkIds: ["verified-restaurant-website", "verified-cafe-captions", "verified-menu-redesign"],
    },
    {
      id: "maya-chen-verified",
      name: "Maya Chen",
      initials: "MC",
      level: "L2 Hatcher",
      rating: "4.9",
      completedCount: 28,
      joinedAt: "Feb 2026",
      specialization: "Local Services Content",
      skills: ["ChatGPT", "Canva", "Website copy", "Customer replies", "Content calendars"],
      industries: ["Restaurant", "Local Services"],
      averageCompletion: "2.1 days",
      totalEarned: "$3,120",
      recentWorkIds: ["verified-cleaning-website", "verified-barber-booking"],
    },
    {
      id: "eli-morgan-verified",
      name: "Eli Morgan",
      initials: "EM",
      level: "L3 Specialist",
      rating: "4.8",
      completedCount: 41,
      joinedAt: "Jan 2026",
      specialization: "E-commerce Operations",
      skills: ["Claude", "ChatGPT", "Sheets", "Zapier", "Shopify content"],
      industries: ["E-commerce", "Education"],
      averageCompletion: "3.4 days",
      totalEarned: "$6,450",
      recentWorkIds: ["verified-skincare-products", "verified-store-faq"],
    },
    {
      id: "samira-patel-verified",
      name: "Samira Patel",
      initials: "SP",
      level: "L2 Hatcher",
      rating: "4.8",
      completedCount: 24,
      joinedAt: "Apr 2026",
      specialization: "Service Business Admin",
      skills: ["ChatGPT", "Google Sheets", "Notion", "Data cleanup", "Reply templates"],
      industries: ["Local Services", "Education"],
      averageCompletion: "1.8 days",
      totalEarned: "$2,760",
      recentWorkIds: ["verified-customer-sheets", "verified-tutoring-landing"],
    },
    {
      id: "noah-kim",
      name: "Noah Kim",
      initials: "NK",
      level: "L3 Specialist",
      rating: "5.0",
      completedCount: 19,
      joinedAt: "May 2026",
      specialization: "Workflow Builder",
      skills: ["Zapier", "Google Forms", "Sheets", "ChatGPT", "Automation notes"],
      industries: ["Local Services", "Real Estate"],
      averageCompletion: "3.1 days",
      totalEarned: "$4,220",
      recentWorkIds: ["verified-barber-booking", "verified-real-estate-leads"],
    },
  ],

  completedHatches: [
    {
      id: "verified-restaurant-website",
      title: "Restaurant Website Refresh",
      clientContext: "The client runs a local cafe and needed a clearer website section for menu items, opening hours, and bookings.",
      objective: "Update the page copy and structure so customers can understand the cafe offer and book faster.",
      scope: ["Rewrite homepage copy", "Add menu section structure", "Create booking CTA", "Prepare handoff notes"],
      deliverables: ["Updated website copy", "Menu section outline", "Booking CTA text", "Editable handoff notes"],
      industry: "Restaurant",
      category: "Website",
      level: "L2",
      amountEarned: "$180",
      completionTime: "2 days",
      rating: "4.9",
      outcome: "Updated copy, menu section, and booking CTA for a local cafe.",
      completedAt: "2026-06-28",
      verifiedBadges: ["Client accepted", "Paid", "Completed"],
      hatcherId: "toby-cheng",
      showProfile: true,
      showEarnings: true,
      showCompletionTime: true,
    },
    {
      id: "verified-cleaning-website",
      title: "Build a one-page website for a local cleaning service",
      clientContext: "The client runs a small cleaning service and needed a simple web presence for services, pricing, and enquiries.",
      objective: "Create a mobile-friendly one-page website brief that turns visitors into enquiries.",
      scope: ["Write homepage copy", "Structure service sections", "Add pricing blocks", "Create contact CTA", "Prepare implementation notes"],
      deliverables: ["Homepage layout draft", "Website copy", "Service section content", "Contact CTA", "Mobile-friendly structure"],
      industry: "Local Services",
      category: "Website",
      level: "L2",
      amountEarned: "$220",
      completionTime: "3 days",
      rating: "4.8",
      outcome: "Produced a clear one-page structure with services, pricing, and enquiry CTA.",
      completedAt: "2026-06-24",
      verifiedBadges: ["Client accepted", "Paid", "Completed"],
      hatcherId: "maya-chen-verified",
      showProfile: true,
      showEarnings: true,
      showCompletionTime: true,
    },
    {
      id: "verified-cafe-captions",
      title: "Create 30 Instagram captions for a cafe",
      clientContext: "The client had a menu and daily specials but no consistent social posting system.",
      objective: "Turn menu items and cafe updates into usable Instagram captions.",
      scope: ["Review menu items", "Create caption angles", "Write 30 captions", "Group posts by theme"],
      deliverables: ["30 captions", "Caption categories", "Hashtag suggestions", "Posting notes"],
      industry: "Restaurant",
      category: "Social Content",
      level: "L1",
      amountEarned: "$90",
      completionTime: "6 hours",
      rating: "5.0",
      outcome: "Delivered a month of caption copy organized by menu item and promotion type.",
      completedAt: "2026-06-22",
      verifiedBadges: ["Client accepted", "Paid", "Completed"],
      hatcherId: "toby-cheng",
      showProfile: true,
      showEarnings: true,
      showCompletionTime: true,
    },
    {
      id: "verified-skincare-products",
      title: "Rewrite Shopify product descriptions for a skincare store",
      clientContext: "The client sells skincare products and needed clearer descriptions for comparison and search.",
      objective: "Rewrite product descriptions so customers can understand benefits and choose products faster.",
      scope: ["Review product list", "Rewrite descriptions", "Clean up product titles", "Add SEO notes"],
      deliverables: ["Updated product descriptions", "Short product summaries", "SEO title suggestions", "Tone cleanup notes"],
      industry: "E-commerce",
      category: "Product Content",
      level: "L2",
      amountEarned: "$260",
      completionTime: "4 days",
      rating: "4.8",
      outcome: "Cleaned up 26 product descriptions with clearer benefits and search-friendly wording.",
      completedAt: "2026-06-20",
      verifiedBadges: ["Client accepted", "Paid", "Completed"],
      hatcherId: "eli-morgan-verified",
      showProfile: true,
      showEarnings: true,
      showCompletionTime: true,
    },
    {
      id: "verified-menu-redesign",
      title: "Design a restaurant menu in Canva",
      clientContext: "The restaurant had a long text menu and wanted a cleaner, printable version.",
      objective: "Create an easy-to-read Canva menu with polished item descriptions.",
      scope: ["Organize menu categories", "Rewrite item descriptions", "Create Canva layout", "Prepare editable file"],
      deliverables: ["Menu copy", "Canva menu layout", "Editable file", "Print-ready notes"],
      industry: "Restaurant",
      category: "Design",
      level: "L2",
      amountEarned: "$70",
      completionTime: "1 day",
      rating: "4.8",
      outcome: "Delivered a cleaner menu layout with updated item descriptions and category structure.",
      completedAt: "2026-06-18",
      verifiedBadges: ["Client accepted", "Paid", "Completed"],
      hatcherId: "toby-cheng",
      showProfile: true,
      showEarnings: true,
      showCompletionTime: true,
    },
    {
      id: "verified-customer-sheets",
      title: "Organize customer contacts in Google Sheets",
      clientContext: "The client had a messy contact list with duplicates and inconsistent columns.",
      objective: "Turn customer data into a clean sheet that can be searched and updated easily.",
      scope: ["Review current data", "Create column structure", "Clean duplicate entries", "Add notes for future updates"],
      deliverables: ["Clean spreadsheet", "Column structure", "Duplicate notes", "Update instructions"],
      industry: "Local Services",
      category: "Admin",
      level: "L1",
      amountEarned: "$110",
      completionTime: "2 days",
      rating: "4.7",
      outcome: "Cleaned and organized 420 contacts into a usable Google Sheets structure.",
      completedAt: "2026-06-16",
      verifiedBadges: ["Client accepted", "Paid", "Completed"],
      hatcherId: "samira-patel-verified",
      showProfile: true,
      showEarnings: false,
      showCompletionTime: true,
    },
    {
      id: "verified-store-faq",
      title: "Create FAQ reply templates for an online store",
      clientContext: "The store owner wanted faster replies for shipping, returns, sizing, and order status questions.",
      objective: "Create reusable customer reply templates that are clear and consistent.",
      scope: ["Group common questions", "Draft reply templates", "Add tone notes", "Create escalation notes"],
      deliverables: ["Reply library", "FAQ grouping", "Tone guide", "Escalation notes"],
      industry: "E-commerce",
      category: "Customer Support",
      level: "L2",
      amountEarned: "$140",
      completionTime: "2 days",
      rating: "4.9",
      outcome: "Delivered 34 reusable reply templates grouped by customer situation.",
      completedAt: "2026-06-14",
      verifiedBadges: ["Client accepted", "Paid", "Completed"],
      hatcherId: "eli-morgan-verified",
      showProfile: true,
      showEarnings: true,
      showCompletionTime: false,
    },
    {
      id: "verified-tutoring-landing",
      title: "Draft a tutoring studio landing page",
      clientContext: "The client runs a tutoring studio and needed landing page copy for parents.",
      objective: "Create clear page copy that explains subjects, session options, and trial booking.",
      scope: ["Write page sections", "Create parent-focused messaging", "Add trial session CTA", "Prepare editable copy"],
      deliverables: ["Landing page copy", "Section structure", "CTA copy", "FAQ block"],
      industry: "Education",
      category: "Website Copy",
      level: "L2",
      amountEarned: "$170",
      completionTime: "3 days",
      rating: "4.9",
      outcome: "Prepared parent-friendly landing page copy with trial booking CTA.",
      completedAt: "2026-06-11",
      verifiedBadges: ["Client accepted", "Paid", "Completed"],
      hatcherId: "samira-patel-verified",
      showProfile: false,
      showEarnings: true,
      showCompletionTime: true,
    },
    {
      id: "verified-barber-booking",
      title: "Build a simple booking workflow for a barber shop",
      clientContext: "The barber shop wanted a lightweight booking request process without adding complex software.",
      objective: "Set up a simple request workflow using Google Forms and Sheets.",
      scope: ["Create booking form fields", "Set up tracking sheet", "Add notification notes", "Write handoff instructions"],
      deliverables: ["Google Form structure", "Tracking sheet", "Workflow notes", "Client handoff guide"],
      industry: "Local Services",
      category: "Operations",
      level: "L3",
      amountEarned: "$320",
      completionTime: "5 days",
      rating: "5.0",
      outcome: "Built a simple booking request flow with a clean tracking sheet and handoff guide.",
      completedAt: "2026-06-08",
      verifiedBadges: ["Client accepted", "Paid", "Completed"],
      hatcherId: "noah-kim",
      showProfile: true,
      showEarnings: true,
      showCompletionTime: true,
    },
    {
      id: "verified-real-estate-leads",
      title: "Create a real estate lead qualification workflow",
      clientContext: "The client needed a simple way to sort buyer and seller enquiries before follow-up.",
      objective: "Create a lightweight qualification workflow for real estate leads.",
      scope: ["Define lead fields", "Create qualification logic", "Draft follow-up templates", "Prepare tracking sheet notes"],
      deliverables: ["Lead form outline", "Qualification rules", "Follow-up templates", "Tracking sheet structure"],
      industry: "Real Estate",
      category: "Workflow",
      level: "L3",
      amountEarned: "$480",
      completionTime: "1 week",
      rating: "4.8",
      outcome: "Created a practical lead intake workflow with qualification logic and follow-up copy.",
      completedAt: "2026-06-05",
      verifiedBadges: ["Client accepted", "Paid", "Completed"],
      hatcherId: "noah-kim",
      showProfile: true,
      showEarnings: false,
      showCompletionTime: false,
    },
  ],

  levels: [
    ["L1", "Simple support Hatches", "Clear, low-risk work like captions, formatting, summaries, and data cleanup."],
    ["L2", "Practical business Hatches", "Useful deliverables like simple websites, menus, product copy, and reply templates."],
    ["L3", "Specialized Hatches", "More complex setup work like automations, content systems, and workflow improvements."],
    ["L4", "Advanced strategy", "Higher-trust strategic work. Coming later."],
  ],
};
